name: CI
on: push

env:
  CI: true
  MONGODB_HOST: "mongodb://localhost:27017/test"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: "4.4"
      - name: Install modules
        run: npm install
      - name: Run unit tests
        run: npm test unit
      - name: Run integration tests
        run: npm test int
      - name: Run coverage test
        run: npm test -- --coverage
      - name: Run eslint
        run: npm run eslint
