name: CI
on: push

env:
  MONGODB_HOST: "MONGODB_HOST"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install modules
        run: npm install
      - name: Run unit tests
        run: npm test unit
      - name: Run integration tests
        run: npm test unit
      - name: Run coverage test
        run: npm test -- --coverage
      - name: Run eslint
        run: npm run eslint
